### ISSUE TITLE
Server crashing when Hitting/Activating Lightsaber.

### ISSUE THREAD

**Issue by Nightmane** [FiskFille/AdvancedLightsabers#11]
So I wanted to do a Lightsaber play with my friend on his server. We have absolutely 0 mods except for the Advanced Lightsabers Mod. However, when I grab a lightsaber to test and right click, sometimes the server crashes. And on the occasions that it doesn't, every time I click to hit something, it DOES crash. Any fix?

**Comment by C0deMaver1ck** [comment]
This was fixed by 2bc622e and is already in master.
