### ISSUE TITLE
Config empty with nothing in it and not taking damage

### ISSUE THREAD

**Issue by Rukia1727** [FiskFille/AdvancedLightsabers#20]
Okay so i love this mod to death but not taking mele damage is a bit too overpowered and the config file is just blank, nothing in it (I went into after I played with the mod for a good hour) so can you please make it so that the config can actually work and that the ability to take mele damage is a toggable feature

**Comment by cloakable** [comment]
Um, what. Yes, the config file being empty is something that needs fixing, but having just been through a Roguelike Dungeons dungeon with a lightsaber, I can assure you I took a ton of melee damage from the mobs there.
