### ISSUE TITLE
Can't Download

### ISSUE THREAD

**Issue by EmrysGamer** [FiskFille/AdvancedLightsabers#22]
Fisk Can You Post A Tutorial on how to download this??

i've been DECIPHERING it for 5hours and still can't figure! please help me!

**Comment by FiskFille** [comment]
[Press the big, orange download button.](https://minecraft.curseforge.com/projects/advanced-lightsabers)
![screenshot_1](https://cloud.githubusercontent.com/assets/10811084/17411612/41042ac0-5a79-11e6-8ce5-36fd2c6deea6.png)

**Comment by EmrysGamer** [comment]
ummm the New Source Code

**Comment by FiskFille** [comment]
Why are you trying to download the source code?

**Comment by EmrysGamer** [comment]
nothing, i figured it's like the "Superheroes Mod" source code.. Wait does it work?

**Comment by EmrysGamer** [comment]
nvm
