### ISSUE TITLE
Texture fail

### ISSUE THREAD

**Issue by yagizcamo93** [FiskFille/AdvancedLightsabers#23]
Some of the saber parts are purple.

![1](https://cloud.githubusercontent.com/assets/21247372/18563221/82117c98-7b8f-11e6-9d04-eb5408283a0e.png)
![2](https://cloud.githubusercontent.com/assets/21247372/18563222/822f4ebc-7b8f-11e6-8af2-ee58a25970be.png)

**Comment by emirotheking** [comment]
me too plz help

**Comment by FiskFille** [comment]
Could you send me your game log?
If you don't know how to do this,
![image](https://cloud.githubusercontent.com/assets/10811084/22029615/617b0596-dcdb-11e6-8fca-3357f8697863.png)
![image](https://cloud.githubusercontent.com/assets/10811084/22029627/65e336bc-dcdb-11e6-9e6f-bdacec053f61.png)

After that, go into your game and make sure it's still happening, and then send me a [Paste](http://pastebin.com/) of all the text in your launcher

**Comment by AlphaPack02** [comment]
ı tried and still same  ı am sorry my log 
http://pastebin.com/hMRLRj1L

**Comment by FiskFille** [comment]
Yes, but I need your game output to see what's going on.

**Comment by AlphaPack02** [comment]
what do you mean? ı copied that log from output

**Comment by FiskFille** [comment]
Ah. I must've seen your message before you added the link, then.
Anyway, the issue has to do with your system's default Locale, where Turkish character sets get in the way. It tries to get the lowercase 'I' and expects 'i'. Instead, 'ı' (Turkish dotless 'i') is returned.

The only quick fix I know of involves setting your system's language to another.

**Comment by AlphaPack02** [comment]
thank you for help
I am using windows 10 Turkish should ı change language ? or just minecraft's language
I get it okey 
I will change my system's language . Thank you .if it work  I will write.

**Comment by AlphaPack02** [comment]
it worked. Thank you so much . Good days
