### ISSUE TITLE
spam and freezing on server

### ISSUE THREAD

**Issue by Cronosus** [FiskFille/AdvancedLightsabers#26]
Helo
When i have your mod on my server, it spams in console and sometimes freeze server
"java.lang.NullPointerException"
http://cronos.wz.cz/mc/lightsabers-spam.log

mc version: 1.7.10
mod version: 1.1
server thermos build 58

thanks in advance for help

**Comment by FiskFille** [comment]
What makes you certain that it's caused by Advanced Lightsabers?

**Comment by Cronosus** [comment]
you can see this many times in console
http://pastebin.com/6HTBMwY6
http://pastebin.com/cqF3kgE1
when is too much lines, game freezes (server cant handle soo many records).

**Comment by FiskFille** [comment]
That's a different thing and has nothing to do with your problem.

**Comment by Cronosus** [comment]
ok, but this spam is still annoying

**Comment by FiskFille** [comment]
Has this issue persisted, as of AL 1.1.1?

**Comment by Cronosus** [comment]
not tried yet
ill try now

edit: no, i not see it anymore. :)

**Comment by FiskFille** [comment]
Woo! \o/
