### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by wormzjl** [FiskFille/AdvancedLightsabers#30]

**Comment by AnrDaemon** [comment]
Bump?

**Comment by FiskFille** [comment]
The mod has been out of development for about 4 ½ years now, so any change to this is very very unlikely.

**Comment by AnrDaemon** [comment]
Your statement has a missing "by me" clause.
People looking for fixes and improvements could do so by themselves, but without a license, it is uncertain if they can distribute them without fear of being taken in court.
Please https://blog.codinghorror.com/pick-a-license-any-license/

GPL2, MIT or even WTFPL would be better than no license. (Please no "public domain", as its legal state is questionable in some countries.)

**Comment by AnrDaemon** [comment]
🥳 🎉
