### ISSUE TITLE
Force Abilities breaking mounts.

### ISSUE THREAD

**Issue by nerdiestmaximus** [FiskFille/AdvancedLightsabers#31]
I was designing a tutorial this morning for a modpack, and I was showing off galacticraft and how to get into the ship, I realised I couldn't get in by right clicking since the force abilities replace the right click key. I used /force take and the jedi philosophy is stuck in my force selection bar, rendering any mounts useless. The advanced lightsaber mod is crucial in this pack, and it would be really helpful if you fixed this really annoying bug, if the dev has stopped working on this, can someone get me their email or leave a suggestion.

**Comment by FiskFille** [comment]
You can remove powers from the hotbar by shift-clicking them in the Force selection menu. This should clear out the specified slot, leaving your right click free for other actions.

**Comment by nerdiestmaximus** [comment]
Thank you so much,
