### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by morbidretrospect** [FiskFille/AdvancedLightsabers#35]
Hi. First time trying your mod out (it was very interesting and it fit my sci-fi themed playthrough) but I can't seem to start my game with your mod installed. Any idea why? Thanks in advance for any help you can give. I'm eager to resume my playthrough with your mod installed.

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 9/5/17 6:45 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: java.lang.reflect.Type.getTypeName()Ljava/lang/String;
	at fiskfille.lightsabers.common.data.ALData.<clinit>(ALData.java:369)
	at fiskfille.lightsabers.common.data.ALPlayerData.createDataMap(ALPlayerData.java:35)
	at fiskfille.lightsabers.common.data.ALPlayerData.<init>(ALPlayerData.java:22)
	at fiskfille.lightsabers.common.event.CommonEventHandler.onEntityConstruct(CommonEventHandler.java:194)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_32_CommonEventHandler_onEntityConstruct_EntityConstructing.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.entity.Entity.<init>(Entity.java:179)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:119)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:141)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:138)
	at net.minecraft.server.management.ServerConfigurationManager.func_148545_a(ServerConfigurationManager.java:410)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:101)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:60)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:215)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 355061888 bytes (338 MB) / 930779136 bytes (887 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D6 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	FamiliarsAPI{1.7.10} [Familiars API] (FamiliarsAPI-1.7.10.jar) 
	UCHIJAAAA	lightsabers{1.1.1} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-1.1.1.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	ArchitectureCraft{1.4.1} [ArchitectureCraft] (ArchitectureCraft-1.4.1-mc1.7.10.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
	UCHIJAAAA	CraftableGunpowder{2.0.0} [CraftableGunpowder] (Craftable Gunpowder.jar) 
	UCHIJAAAA	csaddle{1.2} [Craftable Saddles] (Craftable Saddles mc 1.7.10.jar) 
	UCHIJAAAA	CreeperConfetti{1.0} [CreeperConfetti] (CreeperConfetti-1.0.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar) 
	UCHIJAAAA	DynamicLights{1.3.9a} [Dynamic Lights] (Dynamic Lights-1.3.9a-MC1.7.10.jar) 
	UCHIJAAAA	dsurround{1.0.5.6} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.5.6.jar) 
	UCHIJAAAA	fairylights{1.4.0} [Fairy Lights] (fairylights-1.4.0-1.7.10.jar) 
	UCHIJAAAA	DefaultMobPack{1.7.10} [DefaultMobPack] (FamiliarsDefaultMobPack-1.7.10.jar) 
	UCHIJAAAA	ExtendedFamPack{1.7.10} [ExtendedFamPack] (FamiliarsExtendedFamPack-1.7.10.jar) 
	UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans-Mod-1.7.10.jar) 
	UCHIJAAAA	IC2{2.2.822-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.822-experimental.jar) 
	UCHIJAAAA	FloodLights{1.1.1-120} [Flood Lights] (FloodLights-1.7.10-1.1.1-120.jar) 
	UCHIJAAAA	FoodExpansion{1.0} [Food Expansion] (FoodExpansion1.1.1-mc1.7.10.jar) 
	UCHIJAAAA	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212-Core-1.7.10.jar) 
	UCHIJAAAA	gwycraft{0.1.10} [GwyCraft] (gwycraft-mc1710-0.1.10.jar) 
	UCHIJAAAA	HardcoreDarkness{1.7} [Hardcore Darkness] (HardcoreDarkness-MC1.7.10-1.7.jar) 
	UCHIJAAAA	wuppy29_harderpeaceful{1.7.3} [Harder Peaceful] (Harder Peaceful 1.7.10-1.7.3.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJAAAA	instantblocks{1.5.4} [Instant Blocks] (InstantBlocks_v1.5.4.jar) 
	UCHIJAAAA	InvisibLights{2.3-7} [InvisibLights] (InvisibLights-2.3-7.jar) 
	UCHIJAAAA	reaper_lantern{1.47} [Lantern mod] (Lantern1.47[1.7.10] (1).jar) 
	UCHIJAAAA	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAAAA	MobAmputation{4.0.1} [MobAmputation] (MobAmputation-4.0.1.jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	MSM3{3.0.0d} [More Swords 3] (MSM-SNAP-3.0.0e-For-MC-1.7.10.jar) 
	UCHIJAAAA	MutantCreatures{1.4.9} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.9.jar) 
	UCHIJAAAA	fodc{1.6.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.6.1.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJAAAA	packchevsky{b5} [Potion Packs] (PotionPacks_1.7.10_b5.zip) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJAAAA	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHIJAAAA	RottenFleshToLeather{1.7.10-2.0} [Rotten Flesh to Leather] (RottenFleshToLeather-2.1-1.7.10.jar) 
	UCHIJAAAA	superslopes{V0.1 - 1.7.10} [Super Slopes] (Super-Slopes-Mod-1.7.10.jar) 
	UCHIJAAAA	superminer_core{[1.7.10]-2.1.7.221} [SuperMiner] (SuperMiner-[1.7.10]-2.1.7.221.jar) 
	UCHIJAAAA	superminer_captivator{[1.7.10]-2.1.7.221} [SuperMiner Captivator] (SuperMiner-[1.7.10]-2.1.7.221.jar) 
	UCHIJAAAA	superminer_cropinator{[1.7.10]-2.1.7.221} [SuperMiner Copinator] (SuperMiner-[1.7.10]-2.1.7.221.jar) 
	UCHIJAAAA	superminer_excavator{[1.7.10]-2.1.7.221} [SuperMiner Excavator] (SuperMiner-[1.7.10]-2.1.7.221.jar) 
	UCHIJAAAA	superminer_illuminator{[1.7.10]-2.1.7.221} [SuperMiner Illuminator] (SuperMiner-[1.7.10]-2.1.7.221.jar) 
	UCHIJAAAA	superminer_lumbinator{[1.7.10]-2.1.7.221} [SuperMiner Lumbinator] (SuperMiner-[1.7.10]-2.1.7.221.jar) 
	UCHIJAAAA	superminer_shaftanator{[1.7.10]-2.1.7.221} [SuperMiner Shaftanator] (SuperMiner-[1.7.10]-2.1.7.221.jar) 
	UCHIJAAAA	superminer_substitutor{[1.7.10]-2.1.7.221} [SuperMiner Substitutor] (SuperMiner-[1.7.10]-2.1.7.221.jar) 
	UCHIJAAAA	superminer_veinator{[1.7.10]-2.1.7.221} [SuperMiner Veinator] (SuperMiner-[1.7.10]-2.1.7.221.jar) 
	UCHIJAAAA	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
	UCHIJAAAA	WIT{1.0.8} [WIT] (WIT-1.7.10-1.0.8-1.jar) 
	UCHIJAAAA	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.4.0 - Build 21.20.16.4627
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by FiskFille** [comment]
You need to update your Java.

**Comment by morbidretrospect** [comment]
Thank you. It works now.
