### ISSUE TITLE
Server Crash - GuiScreen

### ISSUE THREAD

**Issue by awitkowski0** [FiskFille/AdvancedLightsabers#52]
I'm sure you guys already know about this one, but it's not posted anywhere, so I thought maybe I should post it just in case.

`24.11 18:33:26 [Server] ERROR Caught exception from lightsabers
24.11 18:33:26 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen`

Full report: 
[crash-2019-11-24_18.33.26-server.txt](https://github.com/FiskFille/AdvancedLightsabers/files/3883927/crash-2019-11-24_18.33.26-server.txt)

**Comment by chrislightsaber** [comment]
I too am having this issue, simply making a server with the lightsaber mod causes this crash

**Comment by FiskFille** [comment]
Fixed in 1.2.2
