### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KamiSami** [FiskFille/AdvancedLightsabers#57]
Hi! I've been eyeing on some good mods and this one strikes pretty impressive, although unfortunately it appears this has not been updates in little while, so i was wondering when i looked around a bit and saw some edit in code section? So i got curious, is this mod still being worked on? If so, will it remain on 1.7.10 or move on to newer versions? If so, which?

**Comment by FiskFille** [comment]
Both yes and no. While the mod isn't actively being worked on at the moment, it's not something I'm ruling out for the future. At the moment, I unfortunately don't have the time to do so, as I am preoccupied with other projects.

But were this mod to get an update, a port to whichever is the most recent active modded version would probably be on the docket.
