### ISSUE TITLE
A fatal error has occured, this connection is terminated 

### ISSUE THREAD

**Issue by ObviouslyTaxi** [FiskFille/AdvancedLightsabers#60]
When attacking with the lightsabre, it will occasionally completely crash the server whether its a single player or multiplayer, any fix for this because I was really looking forward to this mod

**Comment by FiskFille** [comment]
Can you provide a crash log?

**Comment by ObviouslyTaxi** [comment]
I was able to find out the problem, apparently the morph mod I had was clashing with it and was providing problems causing the whole thing to crash but its amazing to see the quick response, thanks anyway
