### ISSUE TITLE
No key config options to use force ability

### ISSUE THREAD

**Issue by Grimmy347** [FiskFille/AdvancedLightsabers#69]
I have learned my first force ability, heal. I am attempting to using it but when I go to the key config in the menu, there is only a menu option for toggling between abilities. I do not know how to assign them or use them if there are no options to assign those actions to key. Any help would be appreciated. This is version 1.1.1

**Comment by FiskFille** [comment]
To open your Force selection screen, you have to press and hold the Force selection keybind. Once open, you can drag-and-drop (or left/right-click) on your available to Force powers to assign/unassign them.
