### ISSUE TITLE
Crash with NEI Render

### ISSUE THREAD

**Issue by HalestormXV** [FiskFille/AdvancedLightsabers#9]
There seems to be a crash relating to NEI perhaps. Granted I do have a lot of mods in this pack but I was careful in crafting the pack and the stack trace indicated specifically something with the rendering. Here is the log. Hopefully it can be fixed. For now I just have users being redirected to the site for a recipe list. Version 1.7.10-1.0.3

http://pastebin.com/GC7in5Xb

**Comment by FiskFille** [comment]
Do you know what you did to trigger the crash?

**Comment by HalestormXV** [comment]
I do. I loaded up a new world. Did a search in NEI and found the items to check some recipes.  Click on one of the recipes that I image you get from a chest as a reward for what I would guess is exploring one of the generated structures. 

The NEI screen opened up and showed the animation of a chest opening and I imagine what was supposed to happen was the crystal was supposed to rise out but instead crash.
